# This workflow will test the python webserver/HMI

name: flawFinder C

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: flawfinder-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flawfinder-action 
        uses: deep5050/flawfinder-action@master
